"""
Orin.LAB · Setup Wizard
Interactive first-time setup — collects API keys and saves to ~/.orinlab/.env
"""

from __future__ import annotations

import os
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich import box

console = Console()

CONFIG_DIR  = Path.home() / ".orinlab"
CONFIG_FILE = CONFIG_DIR / ".env"


BANNER = """[bold cyan]
 ██████╗ ██████╗ ██╗███╗   ██╗   ██╗      █████╗ ██████╗
██╔═══██╗██╔══██╗██║████╗  ██║   ██║     ██╔══██╗██╔══██╗
██║   ██║██████╔╝██║██╔██╗ ██║   ██║     ███████║██████╔╝
██║   ██║██╔══██╗██║██║╚██╗██║   ██║     ██╔══██║██╔══██╗
╚██████╔╝██║  ██║██║██║ ╚████║   ███████╗██║  ██║██████╔╝
 ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝   ╚══════╝╚═╝  ╚═╝╚═════╝
[/bold cyan]
[dim]AI Research Lab for Crypto Markets · Built on Solana[/dim]"""


def _mask(value: str) -> str:
    if not value or len(value) < 8:
        return "••••••••"
    return value[:4] + "••••" + value[-4:]


def _write_env(config: dict[str, str]) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Orin.LAB — Auto-generated by orinlab setup",
        "# Edit this file to update your config\n",
    ]
    for k, v in config.items():
        if v:
            lines.append(f"{k}={v}")
    CONFIG_FILE.write_text("\n".join(lines), encoding="utf-8")


def _load_existing() -> dict[str, str]:
    existing: dict[str, str] = {}
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()
    return existing


def run_setup() -> None:
    console.print(BANNER)
    console.print(Panel.fit(
        "[bold]Welcome to Orin.LAB Setup[/bold]\n"
        "[dim]This wizard will configure your API keys.[/dim]\n"
        f"[dim]Config saved to: {CONFIG_FILE}[/dim]",
        border_style="cyan",
        box=box.ROUNDED,
    ))

    existing = _load_existing()

    if existing:
        console.print(f"\n[dim]Found existing config at {CONFIG_FILE}[/dim]")
        if not Confirm.ask("Update existing config?", default=False):
            console.print("[green]✓ Using existing config. Run [bold]orinlab bot[/bold] to start.[/green]")
            return

    config: dict[str, str] = dict(existing)

    # ── AI Provider ────────────────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 1 — AI Provider[/bold cyan]")
    console.print("  [dim]1[/dim] Anthropic (Claude) — [link=https://console.anthropic.com]console.anthropic.com[/link]")
    console.print("  [dim]2[/dim] DeepInfra (free tier) — [link=https://deepinfra.com]deepinfra.com[/link]")

    provider_choice = Prompt.ask("Choose provider", choices=["1", "2"], default="1")

    if provider_choice == "1":
        config["AI_PROVIDER"] = "anthropic"
        current = config.get("ANTHROPIC_API_KEY", "")
        hint = f" [dim](current: {_mask(current)})[/dim]" if current else ""
        key = Prompt.ask(f"Anthropic API key{hint}", password=True, default=current or "")
        if key:
            config["ANTHROPIC_API_KEY"] = key
    else:
        config["AI_PROVIDER"] = "deepinfra"
        current = config.get("DEEPINFRA_API_KEY", "")
        hint = f" [dim](current: {_mask(current)})[/dim]" if current else ""
        key = Prompt.ask(f"DeepInfra API key{hint}", password=True, default=current or "")
        if key:
            config["DEEPINFRA_API_KEY"] = key
        config.setdefault("DEEPINFRA_MODEL", "meta-llama/Meta-Llama-3.1-70B-Instruct")
        config.setdefault("DEEPINFRA_VISION_MODEL", "meta-llama/Llama-3.2-90B-Vision-Instruct")

    # ── Telegram ───────────────────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 2 — Telegram Bot[/bold cyan]")
    console.print("  Get your token from [link=https://t.me/BotFather]@BotFather[/link] on Telegram")

    current = config.get("TELEGRAM_BOT_TOKEN", "")
    hint = f" [dim](current: {_mask(current)})[/dim]" if current else ""
    token = Prompt.ask(f"Telegram bot token{hint}", password=True, default=current or "")
    if token:
        config["TELEGRAM_BOT_TOKEN"] = token

    # ── Solana (optional) ──────────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 3 — Solana (optional)[/bold cyan]")
    if Confirm.ask("Configure Solana wallet tracking?", default=False):
        config["SOLANA_RPC_URL"] = Prompt.ask(
            "Solana RPC URL",
            default=config.get("SOLANA_RPC_URL", "https://api.mainnet-beta.solana.com"),
        )
        wallet = Prompt.ask("Wallet address to monitor (leave blank to skip)", default="")
        if wallet:
            config["SOLANA_WALLET_ADDRESS"] = wallet

    # ── Twitter/X (optional) ───────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 4 — Twitter/X Auto Poster (optional)[/bold cyan]")
    if Confirm.ask("Configure Twitter/X posting?", default=False):
        for key_name, label in [
            ("TWITTER_API_KEY", "API Key"),
            ("TWITTER_API_SECRET", "API Secret"),
            ("TWITTER_ACCESS_TOKEN", "Access Token"),
            ("TWITTER_ACCESS_SECRET", "Access Secret"),
        ]:
            current = config.get(key_name, "")
            hint = f" [dim](current: {_mask(current)})[/dim]" if current else ""
            val = Prompt.ask(f"Twitter {label}{hint}", password=True, default=current or "")
            if val:
                config[key_name] = val
        config["AUTO_POST_ENABLED"] = "true" if Confirm.ask("Enable auto-posting?", default=False) else "false"

    # ── Defaults ───────────────────────────────────────────────────────────────
    config.setdefault("LOG_LEVEL", "INFO")
    config.setdefault("SIGNAL_CONFIDENCE_THRESHOLD", "70")
    config.setdefault("SIGNAL_INTERVAL", "300")
    config.setdefault("AUTO_POST_ENABLED", "false")

    # ── Save ───────────────────────────────────────────────────────────────────
    _write_env(config)

    console.print(Panel.fit(
        f"[bold green]✓ Setup complete![/bold green]\n\n"
        f"Config saved to [cyan]{CONFIG_FILE}[/cyan]\n\n"
        "[bold]Next steps:[/bold]\n"
        "  [cyan]orinlab bot[/cyan]     — start Telegram bot\n"
        "  [cyan]orinlab signal[/cyan]  — generate market signals\n"
        "  [cyan]orinlab posts SOL[/cyan] — preview posts",
        border_style="green",
        box=box.ROUNDED,
    ))
